# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: wip_user
  password: <%= ENV["WIP_PROJECTS_DATABASE_PASSWORD"] %>
  host: localhost # Altere conforme a configuração do seu PostgreSQL
  port: 5432 # Altere se o PostgreSQL estiver em uma porta diferente
  timeout: 5000

development:
  <<: *default
  database: wip_projects_development
  # Se necessário, descomente e configure username e password
  # username: wip_user
  # password: <%= ENV["WIP_PROJECTS_DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: wip_projects_test
  # Se necessário, descomente e configure username e password
  # username: wip_user
  # password: <%= ENV["WIP_PROJECTS_DATABASE_PASSWORD"] %>

production:
  <<: *default
  database: wip_projects_production
  username: wip_user
  password: <%= ENV["WIP_PROJECTS_DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %> # Defina o host para produção, por exemplo: "localhost" ou o IP do servidor
  port: <%= ENV["DATABASE_PORT"] %> # Se necessário, defina a porta para produção
